baseurl = "https://youngjookim.github.io/fdr/"
title = "TEST"
theme = "hugo-theme-console"
languageCode = "en-us"

publishDir = "../"
relativeURLs = true
canonifyurls = true

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "about/"
  url = "/docs/about/"

  [[params.navlinks]]
  name = "posts/"
  url = "/docs/posts/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "/docs/photos/"
