baseurl = "https://youngjookim.github.io/fdr/"
title = "Filtered Dimensionality Reduction"
theme = "hugo-theme-console"
languageCode = "en-us"

publishDir = "../docs"
relativeURLs = true
canonifyurls = true

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "experiments/"
  url = "experiments/"
  
  [[params.navlinks]]
  name = "results/"
  url = "results/"
